### PR TITLE
Add core tests

### PR DESCRIPTION
**Pull request by delimitry**
Resolves issue #7.

### CODE REVIEW

**Comment by delimitry** [comment]
@karech @karech review please.

**Comment by nazarov-tech** [comment]
@delimitry excellent job! o_0

..though we still need some sort of instructions how to run these tests.  
Could you please add such thing into readme?

**Comment by delimitry** [comment]
OK

**Comment by delimitry** [comment]
@nazarov-tech I've updated README. Also I've added setup.cfg with pytest config and updated requirements.

**Pull request merged**
